# Generated by Django 2.2 on 2019-04-18 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxmed', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogMessage',
        ),
    ]
