# Generated by Django 2.2 on 2019-04-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('luxmed', '0002_delete_logmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserEmail', models.CharField(max_length=120)),
                ('UserPassword', models.CharField(max_length=120)),
                ('City', models.CharField(max_length=120)),
                ('Service', models.CharField(max_length=60)),
                ('TimeFrom', models.DateTimeField(blank=True)),
                ('TimeTo', models.DateTimeField(blank=True)),
                ('VisitDate', models.DateTimeField(blank=True)),
                ('LastCheck', models.DateTimeField(blank=True)),
                ('WhatsappNr', models.CharField(max_length=11)),
            ],
        ),
    ]
