# Generated by Django 2.2 on 2019-04-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luxmed', '0003_mytask'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuxMedLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LuxMedID', models.IntegerField()),
                ('LocationName', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='LuxMedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LuxMedID', models.IntegerField()),
                ('ServiceName', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='mytask',
            name='City',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luxmed.LuxMedLocation'),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luxmed.LuxMedService'),
        ),
    ]
