# Generated by Django 2.2 on 2019-04-22 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxmed', '0005_auto_20190420_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytask',
            name='LastCheck',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='VisitDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='WhatsappNr',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
